import type { IncomingMessage, ServerResponse } from 'node:http';
import type { Plugin } from 'vite';
import { authenticate, confirmPasswordReset, createUser, getSession, logout, requestPasswordReset, type AuthRole } from './auth-service';
import { answerPolicyQuestion } from './policy-rag-service';

const COOKIE_NAME = 'bm_session';
const ROLES: AuthRole[] = ['Incident Commander', 'Threat Hunter', 'SOC Security Lead', 'Cloud Security Architect'];
function cookieOptions(request: IncomingMessage): string { const secure = request.headers['x-forwarded-proto'] === 'https' || Boolean((request.socket as { encrypted?: boolean }).encrypted); return `HttpOnly; Path=/; SameSite=Lax${secure ? '; Secure' : ''}`; }
function getCookie(request: IncomingMessage): string | undefined { return request.headers.cookie?.split(';').map(value => value.trim()).find(value => value.startsWith(`${COOKIE_NAME}=`))?.slice(COOKIE_NAME.length + 1); }
function ip(request: IncomingMessage): string | undefined { const forwarded = request.headers['x-forwarded-for']; return (Array.isArray(forwarded) ? forwarded[0] : forwarded?.split(',')[0])?.trim() || request.socket.remoteAddress; }
async function readBody(request: IncomingMessage): Promise<Record<string, unknown> | null> { let body = ''; for await (const chunk of request) { body += chunk; if (body.length > 16_384) return null; } try { const parsed: unknown = JSON.parse(body || '{}'); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null; } catch { return null; } }
function text(value: unknown, max = 120): string | null { return typeof value === 'string' && value.trim().length <= max ? value.trim() : null; }
function send(response: ServerResponse, status: number, payload: unknown, headers: Record<string, string> = {}): void { response.statusCode = status; response.setHeader('Content-Type', 'application/json'); Object.entries(headers).forEach(([key, value]) => response.setHeader(key, value)); response.end(JSON.stringify(payload)); }

export function authPlugin(geminiApiKey?: string): Plugin { return { name: 'breach-mirror-auth', configureServer(server) { server.middlewares.use(async (request, response, next) => { if (!request.url?.startsWith('/auth/') && !request.url?.startsWith('/api/policy/')) return next(); const route = request.url.split('?')[0]; const requestIp = ip(request);
  if (request.method === 'POST' && route === '/api/policy/ask') { const sessionUser = getSession(getCookie(request), requestIp); if (!sessionUser) return send(response, 401, { message: 'Session expired. Please login again.' }); const body = await readBody(request); const question = text(body?.question, 500); if (!question) return send(response, 400, { message: 'Enter a question about the security policies.' }); try { return send(response, 200, await answerPolicyQuestion(question, geminiApiKey), { 'Cache-Control': 'no-store' }); } catch { return send(response, 500, { message: 'Unable to search the policy documents right now.' }); } }
  if (request.method === 'GET' && route === '/auth/session') { const sessionToken = getCookie(request); const user = getSession(sessionToken, requestIp); return user ? send(response, 200, { user: { id: user.id, name: user.name, email: user.email, role: user.role } }, { 'Set-Cookie': `${COOKIE_NAME}=${sessionToken}; Max-Age=1800; ${cookieOptions(request)}` }) : send(response, 401, { message: 'Session expired. Please login again.' }); }
  if (request.method === 'POST' && route === '/auth/logout') { logout(getCookie(request), requestIp); return send(response, 200, { ok: true }, { 'Set-Cookie': `${COOKIE_NAME}=; Max-Age=0; ${cookieOptions(request)}` }); }
  const body = await readBody(request); if (!body) return send(response, 400, { message: 'Invalid request.' });
  if (request.method === 'POST' && route === '/auth/register') { const name = text(body.name, 80); const username = text(body.username, 120); const email = text(body.email, 254); const password = typeof body.password === 'string' && body.password.length <= 64 ? body.password : null; const confirmPassword = typeof body.confirmPassword === 'string' && body.confirmPassword.length <= 64 ? body.confirmPassword : null; const role = text(body.role, 60) as AuthRole | null; if (!name || !username || !email || !role || !ROLES.includes(role)) return send(response, 400, { message: 'Please check the registration details.' }); if (password === null || !password) return send(response, 400, { message: 'Password must be 8-64 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.' }); if (confirmPassword === null) return send(response, 400, { message: 'Passwords do not match. Please confirm your password.' }); const result = createUser({ name, username, email, role, password, confirmPassword }, requestIp); if ('message' in result) return send(response, 400, { message: result.message }); return send(response, 201, { message: 'Registration completed successfully.' }); }
  if (request.method === 'POST' && route === '/auth/login') { const identifier = text(body.identifier, 254); const password = typeof body.password === 'string' && body.password.length <= 64 ? body.password : null; if (!identifier || password === null || !password) return send(response, 401, { message: 'Invalid username or password.' }); const result = authenticate(identifier, password, requestIp); if ('message' in result) { const status = result.message.startsWith('Account temporarily locked') ? 423 : 401; return send(response, status, { message: result.message }); } return send(response, 200, { message: 'Login successful.', user: { id: result.user.id, name: result.user.name, email: result.user.email, role: result.user.role } }, { 'Set-Cookie': `${COOKIE_NAME}=${result.token}; Max-Age=1800; ${cookieOptions(request)}` }); }
  if (request.method === 'POST' && route === '/auth/password-reset/request') { const identifier = text(body.identifier, 254); if (identifier) requestPasswordReset(identifier, requestIp); return send(response, 200, { message: 'If an account matches, reset instructions have been issued.' }); }
  if (request.method === 'POST' && route === '/auth/password-reset/confirm') { const token = text(body.token, 200); const password = text(body.password, 64); if (!token || !password || !confirmPasswordReset(token, password, requestIp)) return send(response, 400, { message: 'Unable to reset the password.' }); return send(response, 200, { message: 'Password reset complete. You can now sign in.' }); }
  return send(response, 404, { message: 'Not found.' }); }); } }; }